version: "3.8"

services:
  #PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: brainbudget-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: brainbudget
      POSTGRES_PASSWORD: dev_password_123
      POSTGRES_DB: brainbudget_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U brainbudget"]
      interval: 10s
      timeout: 5s
      retries: 5

  #Redis Cache
  redis:
    image: redis:7-alpine
    container_name: brainbudget-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local


